swagger: '2.0'

# Metadados do documento
info:
  version: "1.0.0"
  title: Bookstore Promotion Catalog

paths:
  # Lista dos recursos.
  /descontos:
    # Operações HTTP associadas a esse recurso
    get:
      # Descrição do verbo
      description: |
        Obtém uma lista de produtos promocionais ou descontos do site.
      # Lista de parâmetros:
      parameters:
        # An example parameter that is in query and is required
        -
          name: app-token
          in: header
          description: Identificador da app
          required: true
          type: string
        -
          name: access-token
          in: header
          description: Identificador do usuário
          required: true
          type: string
        -
          name: _limit
          in: query
          description: Quantidade de itens retornados
          required: true
          type: integer
          format: int32

      # Possíveis respostas para essa operação:
      responses:
        # Response code
        200:
          description: Sucesso
          # Esquema do objeto response
          schema:
            type: array
            items:
              $ref: "#/definitions/desconto"
        401:
          description: Não autorizado
    post:
    # Descrição do verbo
       description: |
        Adiciona um desconto/promo
       parameters:
        # Os parâmetros podem estar no path, na query, no header...
        -
          name: app-token
          in: header
          description: Identificador da app
          required: true
          type: string
        -
          name: desconto
          in: body
          description: Dados do desconto que será criado
          required: false
          schema:
            $ref: '#/definitions/desconto'
       responses:
        # Response code
        200:
          description: Sucesso
          # Esquema do objeto response
          schema:
            $ref: "#/definitions/desconto"
        401:
          description: Não autorizado
  /desconto/{id}:
    get:
      description: |
        Obtém os detalhes de um `Desconto/Promocao` específico.
      # Lista de parâmetros:
      parameters:
        # Os parâmetros podem estar no path, na query, no header...
        -
          name: app-token
          in: header
          description: Identificador da app
          required: true
          type: string
        -
          name: access-token
          in: header
          description: Identificador do usuário
          required: true
          type: string
        -
          name: id
          in: path
          description: Identificador do desconto
          required: true
          type: integer
          format: int32

      # Possíveis respostas para essa operação:
      responses:
        # Response code
        200:
          description: Sucesso
          # Esquema do objeto response
          schema:
            $ref: "#/definitions/desconto"
        401:
          description: Não autorizado

definitions:
  desconto:
    required:
      - id
      - nome
    properties:
      id:
        type: integer
        format: int64
      nome:
        type: string
      descricao:
        type: string
      produto:
        type: string
      precoOriginal:
        type: number
      precoPromocional:
        type: number
      dataInicio:
        type: string
      dataFim:
        type: string
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /engesoft17/Promocoes/1.0.0
schemes:
 - https
